version: '3'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    healthcheck:
      test: curl -f http://localhost:3000/ready || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    platform: linux/amd64