version: '3'

services:
  app:
    build: 
      context: app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - /usr/src/app/node_modules

volumes:
  mongodb: