version: '3.4'

services:
  03_03_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  03_03_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"