version: '3.9'
services:
  api:
    build:
      context: ./express-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/live || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10